[package]
name = "typst_vello"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
typst = { workspace = true }
vello = { workspace = true }
bevy_vello_graphics = { workspace = true }
bevy_utils = "0.14"

[lints]
workspace = true
