[package]
name = "bevy_typst"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.13"
bevy_vello = { version = "0.4", features = ["svg"] }
# typst dependencies
typst = "0.11"
typst-svg = "0.11"
typst-assets = { version = "0.11", features = ["fonts"], optional = true }
comemo = "0.4" # in sync with typst
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std"] }
serde = "1"
ureq = "2"
dirs = "5"
tar = "0.4"
flate2 = "1"
ecow = { version = "0.2", features = ["serde"] }
env_proxy = "0.4"

[features]
default = ["embed-fonts"]
embed-fonts = ["dep:typst-assets"]
svg = []
vello = []

[lints.clippy]
redundant_type_annotations = "warn"
bool_comparison = "allow"
