[workspace]
resolver = "2"
members = ["crates/*", ]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/velyst"
readme = "README.md"

[workspace.dependencies]
# Bevy dependencies
bevy = { version = "0.14.1", default-features = false }
bevy_vello_graphics = { version = "0.1.0", git = "https://github.com/voxell-tech/bevy_vello_graphics" }
vello = "0.2.1"
vello_svg = "0.3.1"
# Typst dependencies
# typst = "0.11"
typst = { git = "https://github.com/nixon-voxell/typst" }
typst-svg = { git = "https://github.com/nixon-voxell/typst" }
comemo = "0.4" # in sync with typst
unicode-math-class = "0.1" # in sync with typst

[workspace.lints.clippy]
redundant_type_annotations = "warn"
bool_comparison = "allow"

[package]
name = "velyst"
description = "A Typst integration for Vello and Bevy."
exclude = ["/assets/", "/.github/", "/examples/"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
typst_element = { version = "0.1.0", path = "crates/typst_element" }
typst_vello = { version = "0.1.0", path = "crates/typst_vello" }
bevy = { workspace = true }
bevy_vello = { version = "0.6", features = ["svg"] }
bevy_vello_graphics = { workspace = true }
typst = { workspace = true }
typst-svg = { workspace = true }
typst-assets = { version = "0.11", features = ["fonts"], optional = true }
comemo = { workspace = true }
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std"] }

serde = "1"
ureq = "2"
dirs = "5"
tar = "0.4"
flate2 = "1"
ecow = { version = "0.2", features = ["serde"] }
env_proxy = "0.4"
thiserror = "1"

[features]
default = ["embed-fonts", "dev"]
embed-fonts = ["dep:typst-assets"]
dev = [
    # Enable asset hot reloading for native dev builds.
    "bevy/file_watcher",
    # Enable embedded asset hot reloading for native dev builds.
    # "bevy/embedded_watcher",
]

[dev-dependencies]
bevy = "0.14.1"

[lints]
workspace = true
